### ISSUE TITLE
How do I apply changes to a modpack?

### ISSUE THREAD

**Issue by seriousfreezing** [Nolij/Zume#28]
Let's say I want to use your mod and publish it in my modpack. How can I do that since the location of your mod configuration is outside the modpack instance?

**Comment by Nolij** [comment]
Zume will use the instance config folder instead of the global config folder if there's a file named `zume.json5` in the instance config folder. However, I'd recommend just not shipping a config for Zume, and instead allowing your users to use their existing global Zume config from their other instances.
